---
#!/usr/bin/env ansible-playbook
# Install LXDE - THIS IS NOT TESTED - i just wnated to include installing dunst somewhere so that notifications owork
- hosts: desktop
  become: true
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Install LXDE
      ansible.builtin.command: dnf group install lxde-desktop
    - name: Install Dunst for notifications
      ansible.builtin.dnf:
        name: dunst
