---
#!/usr/bin/env ansible-playbook
# This play installs things you need for Golang development
- hosts: desktop
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Install Golang
      become: true
      ansible.builtin.dnf:
        name: golang
